### PR TITLE
Split gaia.js into individual files.

### PR DESCRIPTION
**Pull request by diiorio**
Just the first step in refactoring to improve organization.

### CODE REVIEW

**Comment by Daedo** [comment]
I will work on it, though I think splitting the file into 37 files is a little exessive. One might want to keep the functional components in the same file, to increase readability.

**Comment by diiorio** [comment]
Oh, it's definitely excessive to split things into that many files and leave them like that. But that's the point of bundlers. Separate files for ease of development, but then programmatically merged into one for production.

**Comment by Daedo** [comment]
No I got this. What I meant is, I might split them into fewer files to keep related components in one file. So that we have an branch for work on the files and the gh-pages branch for the bundled page.

**Comment by Daedo** [comment]
I've split the files in the last commit.

**Pull request closed without merging**
